version: '3.8'  # Añade esta línea al inicio

services:
  db:
    image: postgres:17.4
    container_name: postgres_inventarios
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: inventarios
    ports:
      - "5433:5432"  # Cambiado a 5433 para evitar conflictos
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    command: [
        "postgres",
        "-c", "max_connections=100",
        "-c", "shared_buffers=128MB"
    ]
    restart: unless-stopped

# Añade esta sección al final
volumes:
  postgres_data:
    driver: local