version: '3.8'

services:
  db:
    image: postgres:17.4
    container_name: inventarios_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: inventarios
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=en_US.UTF-8"  # ¡Nuevo!
      LC_ALL: "en_US.UTF-8"  # ¡Nuevo!
      LANG: "en_US.UTF-8"    # ¡Nuevo!
    ports:
      - "5433:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/backup.dump:/docker-entrypoint-initdb.d/backup.dump
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inventarios"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    